name: CI Workflow for Backend Application
# Trigger the workflow
on:  
  push:
    branches: [ "main" ]
    paths:
       - "backend/**"
       - ".github/workflows/github-action-demo.yml"    
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build-backend:
    name: BE backend-Action build analysis
    runs-on: ubuntu-latest
    timeout-minutes: 8                                
    defaults:
      run:
        working-directory: backend
    permissions:
      contents: read
      packages: write

    steps:
  
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package

    - name: Build and Analyze 
      run: mvn -B verify

    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/docker-backend:02
          context: backend/ 


     