name: Run Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    types:
        [opened,synchronize,reopened]

jobs:
  run_docker_image:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    defaults:
        run:
          working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image from GHCR
        run: docker pull ghcr.io/${{ github.repository_owner }}/docker-backend:01

      - name: Run Docker container
        run: docker run --rm ghcr.io/${{ github.repository_owner }}/docker-backend:01
     
