name: Frontend CI-CD Deployment Using EC2
on:
    push:
        branches:
            - REACT-DEMO
    pull_request:
       types: ["opened","synchronize","reopened"]
       
jobs:
    build:
        name: Frontend CI-CD Analysis
        runs-on: ubuntu-latest
        timeout-minutes: 4
        defaults:
          run:
            working-directory: demo-frontend
        permissions:
            contents: write
            packages: write

        steps: 
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup The Node 
              uses: actions/setup-node@v2
              with:
                node-version: '21'
    
            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  path: ${{ github.workspace }}/frontend/node_modules 
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json')}}
    
            - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
              name: List the state of node modules
              continue-on-error: true
              run: npm list

            - name: Test The Application
              run: |
                npm install
             
            # npm run test
            - name: Build the Application
              run: npm run build

            - name: Login to GHCR Repository
              uses: docker/login-action@v2
              with:
                 registry: ghcr.io
                 username: ${{ github.actor }}
                 password: ${{ secrets.PAT_TOKEN }}
                 
    
            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                context: demo-frontend/
                tags: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:frontend-${{ github.run_number }}
                push: true
 
            - name: Copy the key-pair from secrets to the file
              run: |
                echo "${{ secrets.AWS_KEY_PAIR }}" > first-demo.pem

            - name: Change Permission for private-key file
              run: |
                chmod 400 "first-demo.pem"

            - name: Deploy The Frontend Application
              run: |
                ssh -o StrictHostKeyChecking=no -i first-demo.pem ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}'
                docker -v &&
                docker login --username "${{ github.actor }}" --password "${{ secrets.PAT_TOKEN }}" ghcr.io &&
                docker pull ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:frontend-${{ github.run_number }} &&
                docker stop basic-fe-app || true &&
                docker rm basic-fe-app || true &&
                docker run -d -p 4004:80 --name basic-fe-app ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:frontend-${{ github.run_number }} 
                '
              