name: Java CI with Maven
# Trigger the workflow
on:  
  push:
    branches: [ "main" ]
    paths:
       - "backend/**"
       - ".github/workflows/github-action-demo.yml"    
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: BE Github-Action Service Sonar Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 8                                    
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package


