name: Self Hosted Runner job will execute

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      - name: Run on line script on my runner
        run: |
          echo "Hello, I am running on a self-hosted runner"
          sleep 15
