name: Workflow dispatch

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug


jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Log inputs
        run: |
          echo "Log level: $LEVEL"
        env:
          LEVEL: ${{ github.event.inputs.logLevel }}
        
